[package]
name = "drain"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"

[features]
retain = ["tower"]

[dependencies]
futures = "0.3.15"
tokio = { version = "1", features = ["macros", "sync"] }
tower = { version = "0.4.7", default-features = false, optional = true }

[dev-dependencies]
pin-project = "1"
tokio = { version = "1", features = ["time"] }
tokio-test = "0.4"
