name: Rust PR

on: pull_request

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -A deprecated"
  RUSTUP_MAX_RETRIES: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  ## Required builds

  # Ensures we don't take unintended dependencies.
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - uses: EmbarkStudios/cargo-deny-action@b01e7a8cfb1f496c52d77361e84c1840d8246393
      with:
        command: check bans licenses sources

  # Linting
  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v43-rust
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
      - run: cargo fetch
      - run: cargo clippy --all-targets

  # Enforce automated formatting.
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v43-rust
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - run: cargo fmt -- --check

  # Run all tests.
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v43-rust
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
      - run: cargo fetch
      - run: cargo test
