name: Rust PR

on: pull_request

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -A deprecated"
  RUSTUP_MAX_RETRIES: 10

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v45-rust
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
      - run: cargo fetch
      - run: cargo fmt -- --check
      - run: cargo deny --all-features check bans licenses sources
      - run: cargo deny --all-features check advisories
        continue-on-error: true
      - run: cargo clippy --all-targets --all-features --locked
      - run: cargo nextest run --no-run
      - run: cargo nextest run
