name: Rust PR

on:
  pull_request: {}

jobs:

  ## Required builds

  # Ensures we don't take unintended dependencies.
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: EmbarkStudios/cargo-deny-action@30ecad1d5873c1cc2cad10a33637371ca094768b
      with:
        command: check bans licenses sources

  # Prevent sudden announcement of a new advisory from failing Ci.
  advisories:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: EmbarkStudios/cargo-deny-action@30ecad1d5873c1cc2cad10a33637371ca094768b
      with:
        command: check advisories

  # Linting
  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: rustup component add clippy
      - run: cargo clippy --all-targets

  # Enforce automated formatting.
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  # Run all tests.
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: cargo test
