name: Rust PR

on:
  pull_request: {}

jobs:

  ## Required builds

  # Ensures we don't take unintended dependencies.
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - uses: EmbarkStudios/cargo-deny-action@0ca727bbae7b7b578b9a5f98186caac35aa2a00d
      with:
        command: check bans licenses sources

  # Prevent sudden announcement of a new advisory from failing Ci.
  advisories:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - uses: EmbarkStudios/cargo-deny-action@0ca727bbae7b7b578b9a5f98186caac35aa2a00d
      with:
        command: check advisories

  # Linting
  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - run: rustup component add clippy
      - run: cargo clippy --all-targets

  # Enforce automated formatting.
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  # Run all tests.
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - run: cargo test
