name: Rust PR

on:
  pull_request: {}

jobs:

  ## Required builds

  # Ensures we don't take unintended dependencies.
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
    - uses: EmbarkStudios/cargo-deny-action@ccfac4e084d1dedad50125be4550f87a21ba181e
      with:
        command: check bans licenses sources

  # Prevent sudden announcement of a new advisory from failing Ci.
  advisories:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
    - uses: EmbarkStudios/cargo-deny-action@ccfac4e084d1dedad50125be4550f87a21ba181e
      with:
        command: check advisories

  # Linting
  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: rustup component add clippy
      - run: cargo clippy --all-targets

  # Enforce automated formatting.
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.52.1-buster
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  # Run all tests.
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: cargo test
